# SwiftLint configuration for NeoNV
#
# Threshold tightening progress (toward SwiftLint defaults):
# - line_length: 160/250 (target: 120/200) - max in codebase: 156 chars
# - type_body_length: 500/1035 (target: 250/350) - ContentView at ~1033, only violator
# - function_body_length: 115/150 (target: 50/100) - max in codebase: 111 lines
# - file_length: 750/1200 (target: 500/800) - OrgPreviewView at 746
# - cyclomatic_complexity: 22/35 (target: 10/20) - max in codebase: 21

included:
  - NeoNV

line_length:
  warning: 160
  error: 250
  ignores_urls: true
  ignores_comments: true

type_body_length:
  warning: 500
  error: 1035

function_body_length:
  warning: 115
  error: 150

file_length:
  warning: 750
  error: 1200

cyclomatic_complexity:
  warning: 22
  error: 35

# Disable rules that are too noisy for this project
disabled_rules:
  - todo
  - trailing_whitespace
  - function_parameter_count
  - identifier_name

opt_in_rules:
  - empty_count
  - closure_spacing
